services:
  backend:
    image: ${CUSTOM_IMAGE:-erpnext-custom}:${CUSTOM_TAG:-16-staging-ready}
    pull_policy: never

  configurator:
    image: ${CUSTOM_IMAGE:-erpnext-custom}:${CUSTOM_TAG:-16-staging-ready}
    pull_policy: never

  create-site:
    image: ${CUSTOM_IMAGE:-erpnext-custom}:${CUSTOM_TAG:-16-staging-ready}
    pull_policy: never

  frontend:
    image: ${CUSTOM_IMAGE:-erpnext-custom}:${CUSTOM_TAG:-16-staging-ready}
    pull_policy: never
    volumes:
      - ./resources/core/nginx/nginx-template.conf:/templates/nginx/frappe.conf.template:ro

  queue-long:
    image: ${CUSTOM_IMAGE:-erpnext-custom}:${CUSTOM_TAG:-16-staging-ready}
    pull_policy: never

  queue-short:
    image: ${CUSTOM_IMAGE:-erpnext-custom}:${CUSTOM_TAG:-16-staging-ready}
    pull_policy: never

  scheduler:
    image: ${CUSTOM_IMAGE:-erpnext-custom}:${CUSTOM_TAG:-16-staging-ready}
    pull_policy: never

  websocket:
    image: ${CUSTOM_IMAGE:-erpnext-custom}:${CUSTOM_TAG:-16-staging-ready}
    pull_policy: never
